# Generated by Django 5.1.2 on 2024-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('current_status', models.CharField(choices=[('Professor', 'Professor'), ('Student', 'Student'), ('Alumni', 'Alumni')], max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('passout_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
