# Generated by Django 5.1.2 on 2024-11-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userprofile_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country_name',
        ),
    ]
