# Generated by Django 4.2.5 on 2024-10-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='university_roll_no',
            new_name='student_id',
        ),
    ]
