# Generated by Django 5.1.2 on 2024-11-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_userpostmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostmodel',
            name='user_profile',
        ),
    ]
