# Generated by Django 4.2.5 on 2024-10-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_university_roll_no_userprofile_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
