# Generated by Django 5.1.2 on 2024-11-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_userpostmodel_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostmodel',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='website.userprofile'),
            preserve_default=False,
        ),
    ]
