# Generated by Django 5.1.2 on 2024-11-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostmodel',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
