# Generated by Django 5.1.2 on 2024-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_userpostmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
