# Generated by Django 4.2.5 on 2024-10-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_university_roll_no_userprofile_student_id'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_information_employee', to='website.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_information_college', to='website.userprofile'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_information_email', to='website.userprofile'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='passout_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_information_year', to='website.userprofile'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_information_phone', to='website.userprofile'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_information_student', to='website.userprofile'),
        ),
    ]
