# Generated by Django 5.1.2 on 2024-11-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userinformation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='description',
            field=models.TextField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
