# Generated by Django 5.1.2 on 2024-11-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userinformation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='description',
            field=models.TextField(),
        ),
    ]
