# Generated by Django 5.1.2 on 2024-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_userinformation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
